name       : dejavu-fonts-ttf
version    : 2.35
release    : 2
source     :
    - http://sourceforge.net/projects/dejavu/files/dejavu/2.35/dejavu-fonts-ttf-2.35.tar.bz2 : f6d7965586101ff3a8a5c3ec503e082bb6a9604ff53413e10702e5917c194d88
license    : Copyright
summary    : Font family based on the Bitstream Vera Fonts with a wider range of characters
description: |
    Font family based on the Bitstream Vera Fonts with a wider range of characters
install    : |
    mkdir -p $installdir/usr/share/fontconfig/conf.avail
    mkdir -p $installdir/usr/share/fonts/truetype/dejavu
    
    install -m00644 ttf/*.ttf $installdir/usr/share/fonts/truetype/dejavu/.
    install -m00644 fontconfig/*.conf $installdir/usr/share/fontconfig/conf.avail/.
