name       : dejavu-fonts-ttf
version    : '2.37'
release    : 5
source     :
    - https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.tar.bz2 : fa9ca4d13871dd122f61258a80d01751d603b4d3ee14095d65453b4e846e17d7
license    : Copyright
component  : desktop.font
summary    : Font family based on the Bitstream Vera Fonts with a wider range of characters
description: |
    Font family based on the Bitstream Vera Fonts with a wider range of characters
install    : |
    mkdir -p $installdir/usr/share/fontconfig/conf.avail
    mkdir -p $installdir/usr/share/fonts/truetype/dejavu

    install -m00644 ttf/*.ttf $installdir/usr/share/fonts/truetype/dejavu/.
    install -m00644 fontconfig/*.conf $installdir/usr/share/fontconfig/conf.avail/.
